# ===== Kafka Producer (ingestor) =====
bootstrap.servers=localhost:9092
acks=all
linger.ms=25
batch.size=262144
compression.type=zstd
retries=10
request.timeout.ms=30000
enable.idempotence=true

# Rutas de tus CSV (puedes sobreescribir por variables de entorno)
csv.air=
csv.noise=
csv.und=
