# ===== Kafka Producer (ingestor) =====
bootstrap.servers=localhost:9092
acks=all
linger.ms=25
batch.size=262144
compression.type=gzip   
retries=10
request.timeout.ms=30000
enable.idempotence=true
max.in.flight.requests.per.connection=5
retry.backoff.ms=250
buffer.memory=33554432

# ===== Topics (agregar) =====
topic.air=sensores.air
topic.noise=sensores.noise
topic.underground=sensores.underground

# ===== CSV rutas (las puedes sobreescribir por ENV) =====
csv.air=
csv.noise=
csv.und=

# ===== Progreso/Lotes (opcional) =====
batch.size.rows=10000
progress.every.rows=1000
